name: kamran_zafar_s_application1
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_rating_bar: ^4.0.1
  pin_code_fields: ^8.0.1
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  intl: ^0.18.0
dev_dependencies: 
  flutter_native_splash: ^2.3.7
  flutter_test: 
    sdk: flutter

flutter_native_splash:
  image: assets2/bazar.png,
  # color: "0xFF54408C"

flutter: 
  uses-material-design: true
  assets: 
    - assets/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoSemiBold.ttf
          weight: 600
        - asset: assets/fonts/RobotoBold.ttf
          weight: 700
    - family: Open Sans
      fonts: 
        - asset: assets/fonts/OpenSansRomanBold.ttf
          weight: 700
        - asset: assets/fonts/OpenSansBold.ttf
          weight: 700
        - asset: assets/fonts/OpenSansRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/OpenSansRomanSemiBold.ttf
          weight: 600
    - family: Plus Jakarta Sans
      fonts: 
        - asset: assets/fonts/PlusJakartaSansMedium.ttf
          weight: 500
    - family: Circular Std
      fonts: 
        - asset: assets/fonts/CircularStdBook.ttf
          weight: 500
