import '../home_page/widgets/productcard_item_widget.dart';import '../home_page/widgets/specialoffercomponent_item_widget.dart';import '../home_page/widgets/userprofile1_item_widget.dart';import '../home_page/widgets/widget_item_widget.dart';import 'package:carousel_slider/carousel_slider.dart';import 'package:flutter/material.dart';import 'package:kamran_zafar_s_application1/core/app_export.dart';import 'package:kamran_zafar_s_application1/widgets/app_bar/appbar_leading_image.dart';import 'package:kamran_zafar_s_application1/widgets/app_bar/appbar_subtitle.dart';import 'package:kamran_zafar_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';
// ignore_for_file: must_be_immutable
class HomePage extends StatelessWidget {HomePage({Key? key}) : super(key: key);

int sliderIndex = 1;

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 16.v), child: Padding(padding: EdgeInsets.only(left: 24.h, bottom: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildAutoLayoutVertical(context), SizedBox(height: 28.v), _buildAutoLayoutHorizontal1(context), SizedBox(height: 13.v), _buildProductCard(context), SizedBox(height: 31.v), _buildFrame(context), SizedBox(height: 31.v), _buildAutoLayoutVertical1(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIconSearch, margin: EdgeInsets.only(left: 24.h, top: 34.v, bottom: 8.v), onTap: () {onTapIconSearch(context);}), centerTitle: true, title: AppbarSubtitle(text: "Home", margin: EdgeInsets.only(top: 32.v, bottom: 5.v)), actions: [Container(height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.fromLTRB(24.h, 34.v, 24.h, 8.v), child: Stack(alignment: Alignment.topRight, children: [CustomImageView(imagePath: ImageConstant.imgUserGray90001, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.center, onTap: () {onTapImgUser(context);}), Align(alignment: Alignment.topRight, child: Container(height: 8.adaptSize, width: 8.adaptSize, margin: EdgeInsets.only(left: 13.h, right: 3.h, bottom: 16.v), decoration: BoxDecoration(color: appTheme.red400, borderRadius: BorderRadius.circular(4.h), border: Border.all(color: appTheme.whiteA700, width: 1.h))))]))]); } 
/// Section Widget
Widget _buildAutoLayoutVertical(BuildContext context) { return SizedBox(height: 162.v, width: 327.h, child: Stack(alignment: Alignment.bottomRight, children: [Align(alignment: Alignment.bottomCenter, child: SizedBox(height: 8.v, child: AnimatedSmoothIndicator(activeIndex: 0, count: 3, effect: ScrollingDotsEffect(spacing: 4, activeDotColor: theme.colorScheme.primary, dotColor: theme.colorScheme.onErrorContainer, activeDotScale: 2.0, dotHeight: 4.v, dotWidth: 4.h)))), Align(alignment: Alignment.bottomRight, child: SizedBox(height: 182.v, width: 351.h, child: Stack(alignment: Alignment.bottomRight, children: [CarouselSlider.builder(options: CarouselOptions(height: 182.v, initialPage: 0, autoPlay: true, viewportFraction: 1.0, enableInfiniteScroll: false, scrollDirection: Axis.horizontal, onPageChanged: (index, reason) {sliderIndex = index;}), itemCount: 2, itemBuilder: (context, index, realIndex) {return SpecialoffercomponentItemWidget();}), Align(alignment: Alignment.bottomRight, child: Container(height: 8.v, margin: EdgeInsets.only(bottom: 20.v), child: AnimatedSmoothIndicator(activeIndex: sliderIndex, count: 2, axisDirection: Axis.horizontal, effect: ScrollingDotsEffect(spacing: 4, activeDotColor: theme.colorScheme.primary, dotColor: theme.colorScheme.primaryContainer, activeDotScale: 2.0, dotHeight: 4.v, dotWidth: 4.h))))])))])); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal1(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 22.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Top of Week", style: CustomTextStyles.titleMediumOpenSansBold18), Padding(padding: EdgeInsets.only(bottom: 6.v), child: Text("See all", style: CustomTextStyles.titleSmallPrimaryBold))])); } 
/// Section Widget
Widget _buildProductCard(BuildContext context) { return SizedBox(height: 198.v, child: ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: 7, itemBuilder: (context, index) {return ProductcardItemWidget();})); } 
/// Section Widget
Widget _buildFrame(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(right: 24.h), child: _buildAutoLayoutHorizontal(context, authors: "Best Vendors", seeAll: "See all", onTapSeeAll: () {onTapTxtSeeAll(context);})), SizedBox(height: 15.v), SizedBox(height: 80.v, child: ListView.separated(padding: EdgeInsets.only(left: 15.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 22.h);}, itemCount: 7, itemBuilder: (context, index) {return WidgetItemWidget();}))]); } 
/// Section Widget
Widget _buildAutoLayoutVertical1(BuildContext context) { return Align(alignment: Alignment.centerRight, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(right: 45.h), child: _buildAutoLayoutHorizontal(context, authors: "Authors", seeAll: "See all", onTapSeeAll: () {onTapTxtSeeAll1(context);})), SizedBox(height: 30.v), SizedBox(height: 166.v, width: 372.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.centerRight, child: SizedBox(height: 166.v, child: ListView.separated(padding: EdgeInsets.only(left: 134.h, right: 21.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 30.h);}, itemCount: 2, itemBuilder: (context, index) {return Userprofile1ItemWidget();}))), Align(alignment: Alignment.center, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(height: 102.adaptSize, width: 102.adaptSize, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgEllipse102x102, height: 102.adaptSize, width: 102.adaptSize, radius: BorderRadius.circular(51.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgImage102x102, height: 102.adaptSize, width: 102.adaptSize, radius: BorderRadius.circular(51.h), alignment: Alignment.center)])), CustomImageView(imagePath: ImageConstant.imgImage6, height: 102.adaptSize, width: 102.adaptSize, radius: BorderRadius.circular(51.h))]), SizedBox(height: 16.v), Text("John Freeman", style: theme.textTheme.titleMedium), SizedBox(height: 8.v), Text("Writer", style: CustomTextStyles.bodyMediumGray50001)]))]))])); } 
/// Common widget
Widget _buildAutoLayoutHorizontal(BuildContext context, {required String authors, required String seeAll, Function? onTapSeeAll, }) { return Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(authors, style: CustomTextStyles.titleMediumOpenSansBold18.copyWith(color: appTheme.gray90001)), GestureDetector(onTap: () {onTapSeeAll!.call();}, child: Padding(padding: EdgeInsets.only(left: 213.h, top: 3.v, bottom: 4.v), child: Text(seeAll, style: CustomTextStyles.titleSmallPrimaryBold.copyWith(color: theme.colorScheme.primary))))]); } 
/// Navigates to the menuSearchScreen when the action is triggered.
onTapIconSearch(BuildContext context) { Navigator.pushNamed(context, AppRoutes.menuSearchScreen); } 
/// Navigates to the notificationDeliveryScreen when the action is triggered.
onTapImgUser(BuildContext context) { Navigator.pushNamed(context, AppRoutes.notificationDeliveryScreen); } 
/// Navigates to the homeVendorsTabContainerScreen when the action is triggered.
onTapTxtSeeAll(BuildContext context) { Navigator.pushNamed(context, AppRoutes.homeVendorsTabContainerScreen); } 
/// Navigates to the homeAuthorsTabContainerScreen when the action is triggered.
onTapTxtSeeAll1(BuildContext context) { Navigator.pushNamed(context, AppRoutes.homeAuthorsTabContainerScreen); } 
 }
