import '../cart_confirm_order_payment_method_one_bottomsheet/widgets/autolayoutvertical_item_widget.dart';import 'package:flutter/material.dart';import 'package:kamran_zafar_s_application1/core/app_export.dart';import 'package:kamran_zafar_s_application1/widgets/custom_elevated_button.dart';class CartConfirmOrderPaymentMethodOneBottomsheet extends StatelessWidget {const CartConfirmOrderPaymentMethodOneBottomsheet({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 16.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.customBorderTL32), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(width: 56.h, child: Divider(color: appTheme.gray20001)), SizedBox(height: 17.v), _buildDeliveryDate(context), SizedBox(height: 26.v), _buildDeliveryTime(context), SizedBox(height: 65.v), CustomElevatedButton(text: "Confirm", onPressed: () {onTapConfirm(context);}), SizedBox(height: 47.v)])); } 
/// Section Widget
Widget _buildDeliveryDate(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 1.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Delivery date", style: CustomTextStyles.titleMediumOpenSansBold18), SizedBox(height: 13.v), Wrap(runSpacing: 25.v, spacing: 25.h, children: List<Widget>.generate(3, (index) => AutolayoutverticalItemWidget()))])); } 
/// Section Widget
Widget _buildDeliveryTime(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 1.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Delivery time", style: CustomTextStyles.titleMediumOpenSansBold18), SizedBox(height: 13.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Container(margin: EdgeInsets.only(right: 6.h), padding: EdgeInsets.symmetric(horizontal: 26.h, vertical: 12.v), decoration: AppDecoration.outlinePrimary2.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 4.v), SizedBox(width: 103.h, child: Text("Between\n10PM : 11PM", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleMediumOpenSansBold_1.copyWith(height: 1.50)))]))), Expanded(child: Container(margin: EdgeInsets.only(left: 6.h), padding: EdgeInsets.symmetric(horizontal: 26.h, vertical: 12.v), decoration: AppDecoration.outlineGray200011.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 4.v), SizedBox(width: 103.h, child: Text("Between\n10PM : 11PM", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleMediumOpenSansBold_1.copyWith(height: 1.50)))])))])])); } 
/// Navigates to the cartConfirmOrderVisaAddedScreen when the action is triggered.
onTapConfirm(BuildContext context) { Navigator.pushNamed(context, AppRoutes.cartConfirmOrderVisaAddedScreen); } 
 }
