import '../home_authors_inner_page_screen/widgets/productcard1_item_widget.dart';import 'package:flutter/material.dart';import 'package:kamran_zafar_s_application1/core/app_export.dart';import 'package:kamran_zafar_s_application1/widgets/app_bar/appbar_leading_image.dart';import 'package:kamran_zafar_s_application1/widgets/app_bar/appbar_subtitle.dart';import 'package:kamran_zafar_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:kamran_zafar_s_application1/widgets/custom_rating_bar.dart';class HomeAuthorsInnerPageScreen extends StatelessWidget {const HomeAuthorsInnerPageScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 9.v), child: Padding(padding: EdgeInsets.symmetric(horizontal: 23.h), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgImage124x124, height: 124.adaptSize, width: 124.adaptSize, radius: BorderRadius.circular(62.h)), SizedBox(height: 6.v), Text("Novelist", style: CustomTextStyles.bodyLargeOpenSansGray90001), SizedBox(height: 13.v), Text("Tess Gunty", style: CustomTextStyles.titleLarge_1), SizedBox(height: 19.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomRatingBar(initialRating: 0, itemSize: 28), Padding(padding: EdgeInsets.only(left: 4.h, top: 3.v), child: Text("(4.0)", style: CustomTextStyles.titleMediumOpenSans))]), SizedBox(height: 22.v), Align(alignment: Alignment.centerLeft, child: Text("About ", style: CustomTextStyles.titleMediumOpenSansBold)), SizedBox(height: 8.v), Align(alignment: Alignment.centerLeft, child: Container(width: 317.h, margin: EdgeInsets.only(right: 10.h), child: RichText(text: TextSpan(children: [TextSpan(text: "Gunty was born and raised in ", style: CustomTextStyles.bodyLargeOpenSansGray600), TextSpan(text: "South Bend, Indiana", style: CustomTextStyles.bodyLargeOpenSansGray600), TextSpan(text: ".She graduated from the ", style: CustomTextStyles.bodyLargeOpenSansGray600), TextSpan(text: "University of Notre Dame", style: CustomTextStyles.bodyLargeOpenSansGray600), TextSpan(text: " with a ", style: CustomTextStyles.bodyLargeOpenSansGray600), TextSpan(text: "Bachelor of Arts", style: CustomTextStyles.bodyLargeOpenSansGray600), TextSpan(text: " in English and from ", style: CustomTextStyles.bodyLargeOpenSansGray600), TextSpan(text: "New York University.\n", style: CustomTextStyles.bodyLargeOpenSansGray600)]), textAlign: TextAlign.left))), SizedBox(height: 21.v), Align(alignment: Alignment.centerLeft, child: Text("Products", style: CustomTextStyles.titleMediumOpenSansBold)), SizedBox(height: 14.v), _buildProductCard(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 74.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 15.v, bottom: 16.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitle(text: "Authors")); } 
/// Section Widget
Widget _buildProductCard(BuildContext context) { return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 213.v, crossAxisCount: 2, mainAxisSpacing: 11.h, crossAxisSpacing: 11.h), physics: NeverScrollableScrollPhysics(), itemCount: 6, itemBuilder: (context, index) {return Productcard1ItemWidget();}); } 
/// Navigates to the homeContainerScreen when the action is triggered.
onTapArrowDown(BuildContext context) { Navigator.pushNamed(context, AppRoutes.homeContainerScreen); } 
 }
